name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: npm install

      - name: install cargo install tauri-cli
        run: cargo install tauri-cli@^2.0.0-beta

      - name: run tauri build
        run: cargo tauri build

      - name: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            src-tauri/target/release/bundle/appimage/money-progress_0.1.0_amd64.AppImage
            src-tauri/target/release/bundle/appimage/money-progress_0.1.0_amd64.AppImage
            src-tauri/target/release/bundle/deb/money-progress_0.1.0_amd64.deb
            src-tauri/target/release/bundle/rpm/MoneyProgress-0.1.0-1.x86_64.rpm
